#include <stdio.h>
#include <stdlib.h>

#define LIMIT 4000000
/*
 * Problem: Each new term in the Fibonacci sequence
 *  is generated by adding the previous two terms. By
 *  starting with 1 and 2, the first 10 terms will be:
 *
 *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose
 *   values do not exceed four million, find the sum of the
 *    even-valued terms.
 */
int main(void) {
	int a = 1, b = 2, c = 2;
	int sum = 0;

	while(c < LIMIT){
		if(!(c%2))
			sum += c;

		c = a+b;
		a = b;
		b = c;
	}

	printf("Sum of even terms in Fibonacci below %d: %d\n", LIMIT, sum);
	return 0;
}
